-- Sebetsa local demo seed — placeholder.
--
-- Funda360's original seed (education demo data: schools, learners,
-- guardians, etc.) has been archived at
-- docs/funda360-reference-other/seed.sql as a structural reference (the
-- deterministic-id / relative-date techniques it uses are worth reusing),
-- but its content does not apply to Sebetsa's schema.
--
-- TODO (Phase K): build a Sebetsa demo dataset here — one organization
-- (Servest), a couple of regions/clients/sites, and a small workforce —
-- once the scheduling/attendance/tasks domains exist to seed alongside
-- employees.
