import type { UserRole } from '@/features/auth/types/auth.types';
import type { Permission } from '@/features/rbac/types/permission.types';

/**
 * Elevated permissions per role. Every authenticated role additionally
 * carries an implicit baseline of `profile.view_own` / `profile.update_own`
 * (see hasPermission in utils/permissionHelpers.ts), so those two are
 * deliberately omitted here rather than repeated 9 times.
 *
 * Follows the operational hierarchy: Organisation > Region > Client > Site >
 * Workforce. Write access to org structure (regions/clients/sites/contracts)
 * narrows as seniority decreases; `employee` and `client_user` are
 * deliberately minimal — an employee sees their own schedule/attendance/
 * tasks (enforced by RLS + app-level scoping, not by broader permissions
 * here), and client_user is a Phase 2 client-portal role with nothing to
 * grant yet.
 *
 * department.manage/position.manage mirror the DB's
 * departments_write_by_manager/positions_write_by_manager RLS policies
 * (can_manage_org_structure() OR hr_user — see
 * 20260911101600_workforce_management.sql): organization_administrator,
 * operations_manager, hr_user, platform_administrator. team.manage/
 * site_assignment.manage mirror can_manage_operations() instead — the
 * broader operational tier (regional_manager/site_manager/supervisor too,
 * but not hr_user) — a site_manager builds their own site's team day to
 * day; that isn't an HR function. scheduling.manage/availability.manage
 * follow the same can_manage_operations() tier (see
 * 20260911101700_scheduling_and_availability.sql) — hr_user is deliberately
 * excluded from all three, same reasoning. availability.view is additionally
 * granted to `employee` even though it holds no `.manage` permission — an
 * employee always manages their OWN availability via the RLS self-service
 * carve-out regardless of permissions here (mirrors profile.update_own).
 * Keep this file and those RLS policies in sync if either changes.
 */
export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  platform_administrator: [
    'organization.view',
    'organization.manage',
    'tenant.switch',
    'profile.view_any',
    'profile.manage_any',
    'org_structure.view',
    'org_structure.manage',
    'department.view',
    'department.manage',
    'position.view',
    'position.manage',
    'employee.view',
    'employee.manage',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'leave.view',
    'leave.manage',
    'leave.approve',
    'task.view',
    'task.manage',
    'reports.view',
    'reports.export',
  ],
  organization_administrator: [
    'organization.view',
    'organization.manage',
    'profile.view_any',
    'profile.manage_any',
    'org_structure.view',
    'org_structure.manage',
    'department.view',
    'department.manage',
    'position.view',
    'position.manage',
    'employee.view',
    'employee.manage',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'leave.view',
    'leave.manage',
    'leave.approve',
    'task.view',
    'task.manage',
    'reports.view',
    'reports.export',
  ],
  operations_manager: [
    'organization.view',
    'profile.view_any',
    'org_structure.view',
    'org_structure.manage',
    'department.view',
    'department.manage',
    'position.view',
    'position.manage',
    'employee.view',
    'employee.manage',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'leave.view',
    'leave.manage',
    'leave.approve',
    'task.view',
    'task.manage',
    'reports.view',
    'reports.export',
  ],
  regional_manager: [
    'organization.view',
    'profile.view_any',
    'org_structure.view',
    'department.view',
    'position.view',
    'employee.view',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'leave.view',
    'leave.approve',
    'task.view',
    'task.manage',
    'reports.view',
  ],
  site_manager: [
    'organization.view',
    'org_structure.view',
    'department.view',
    'position.view',
    'employee.view',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'leave.view',
    'task.view',
    'task.manage',
    'reports.view',
  ],
  supervisor: [
    'organization.view',
    'department.view',
    'position.view',
    'employee.view',
    'team.view',
    'team.manage',
    'site_assignment.view',
    'site_assignment.manage',
    'scheduling.view',
    'scheduling.manage',
    'availability.view',
    'availability.manage',
    'attendance.view',
    'attendance.manage',
    'task.view',
    'task.manage',
    'reports.view',
  ],
  hr_user: [
    'organization.view',
    'profile.view_any',
    'profile.manage_any',
    'department.view',
    'department.manage',
    'position.view',
    'position.manage',
    'employee.view',
    'employee.manage',
    'team.view',
    'site_assignment.view',
    'leave.view',
    'leave.manage',
    'leave.approve',
    'reports.view',
    'reports.export',
  ],
  employee: ['scheduling.view', 'availability.view', 'attendance.view', 'task.view', 'leave.view'],
  client_user: [],
};
