/**
 * GENERATED by scripts/generate-db-types.sh from supabase/migrations — do not
 * edit. Column lists and literal defaults of the Sebetsa schema, applied by the
 * E2E fake backend on insert exactly as PostgreSQL would (function defaults —
 * ids, timestamps — are handled in fakeBackend.ts).
 */
/** Every column of every table: omitted nullable columns come back as null, like PostgREST. */
export const TABLE_COLUMNS: Record<string, string[]> = {
  "asset_assignments": [
    "id",
    "tenant_id",
    "asset_id",
    "assigned_to_employee_id",
    "assigned_to_team_id",
    "assigned_to_site_id",
    "assigned_by",
    "assigned_at",
    "returned_at",
    "condition_at_assignment",
    "condition_at_return",
    "reason",
    "created_at"
  ],
  "asset_maintenance_records": [
    "id",
    "tenant_id",
    "asset_id",
    "description",
    "performed_at",
    "cost",
    "performed_by",
    "created_at"
  ],
  "assets": [
    "id",
    "tenant_id",
    "asset_number",
    "name",
    "category",
    "serial_number",
    "site_id",
    "custodian_employee_id",
    "status",
    "condition",
    "acquisition_date",
    "acquisition_cost",
    "notes",
    "created_at",
    "updated_at"
  ],
  "attendance_breaks": [
    "id",
    "tenant_id",
    "attendance_record_id",
    "break_start",
    "break_end",
    "created_at"
  ],
  "attendance_corrections": [
    "id",
    "tenant_id",
    "attendance_record_id",
    "field",
    "previous_value",
    "new_value",
    "reason",
    "status",
    "requested_by",
    "reviewed_by",
    "reviewed_at",
    "review_notes",
    "created_at",
    "updated_at"
  ],
  "attendance_policies": [
    "id",
    "tenant_id",
    "grace_period_minutes",
    "early_departure_threshold_minutes",
    "overtime_threshold_minutes",
    "created_at",
    "updated_at"
  ],
  "attendance_records": [
    "id",
    "tenant_id",
    "shift_id",
    "site_id",
    "employee_id",
    "status",
    "clock_in_at",
    "clock_out_at",
    "recorded_by",
    "notes",
    "created_at",
    "updated_at",
    "late_minutes",
    "early_departure_minutes",
    "worked_minutes",
    "overtime_minutes"
  ],
  "audit_log": [
    "id",
    "tenant_id",
    "actor_profile_id",
    "action",
    "entity_table",
    "entity_id",
    "before",
    "after",
    "created_at",
    "category",
    "outcome",
    "request_id",
    "metadata"
  ],
  "client_contacts": [
    "id",
    "tenant_id",
    "client_id",
    "name",
    "role_title",
    "email",
    "phone",
    "is_primary",
    "notes",
    "created_at",
    "updated_at"
  ],
  "clients": [
    "id",
    "tenant_id",
    "region_id",
    "name",
    "industry",
    "primary_contact_name",
    "primary_contact_email",
    "primary_contact_phone",
    "status",
    "created_at",
    "updated_at"
  ],
  "compliance_records": [
    "id",
    "tenant_id",
    "requirement_id",
    "site_id",
    "client_id",
    "contract_id",
    "responsible_profile_id",
    "status",
    "due_date",
    "completed_date",
    "expiry_date",
    "evidence_storage_path",
    "verified_by",
    "verified_at",
    "notes",
    "created_at",
    "updated_at"
  ],
  "compliance_requirements": [
    "id",
    "tenant_id",
    "name",
    "category",
    "description",
    "applies_to_scope",
    "recurrence_interval_days",
    "is_active",
    "created_by",
    "created_at",
    "updated_at"
  ],
  "contract_documents": [
    "id",
    "tenant_id",
    "contract_id",
    "file_name",
    "mime_type",
    "file_size_bytes",
    "storage_path",
    "version",
    "uploaded_by",
    "created_at"
  ],
  "contract_sites": [
    "contract_id",
    "site_id",
    "tenant_id",
    "created_at"
  ],
  "contracts": [
    "id",
    "tenant_id",
    "client_id",
    "contract_number",
    "start_date",
    "end_date",
    "status",
    "responsible_manager_id",
    "sla_notes",
    "created_at",
    "updated_at"
  ],
  "departments": [
    "id",
    "tenant_id",
    "name",
    "created_at",
    "updated_at"
  ],
  "development_actions": [
    "id",
    "tenant_id",
    "employee_id",
    "review_id",
    "goal",
    "owner_profile_id",
    "target_date",
    "status",
    "completed_at",
    "created_at",
    "updated_at"
  ],
  "employee_availability": [
    "id",
    "tenant_id",
    "employee_id",
    "day_of_week",
    "start_time",
    "end_time",
    "created_at",
    "updated_at"
  ],
  "employee_availability_exceptions": [
    "id",
    "tenant_id",
    "employee_id",
    "exception_date",
    "is_available",
    "start_time",
    "end_time",
    "reason",
    "created_at",
    "leave_request_id"
  ],
  "employee_documents": [
    "id",
    "tenant_id",
    "employee_id",
    "document_type",
    "file_name",
    "mime_type",
    "file_size_bytes",
    "storage_path",
    "version",
    "supersedes_document_id",
    "status",
    "expiry_date",
    "uploaded_by",
    "verified_by",
    "verified_at",
    "review_notes",
    "created_at",
    "updated_at",
    "status_before_archive"
  ],
  "employee_qualifications": [
    "id",
    "tenant_id",
    "employee_id",
    "credential_type",
    "name",
    "issuing_organization",
    "issue_date",
    "expiry_date",
    "status",
    "evidence_document_id",
    "verified_by",
    "verified_at",
    "created_at",
    "updated_at"
  ],
  "employee_skills": [
    "id",
    "tenant_id",
    "employee_id",
    "skill_id",
    "proficiency_level",
    "evidence_document_id",
    "verified_by",
    "verified_at",
    "created_at",
    "updated_at"
  ],
  "employees": [
    "id",
    "tenant_id",
    "profile_id",
    "employee_number",
    "first_name",
    "last_name",
    "email",
    "phone",
    "department_id",
    "position_id",
    "supervisor_id",
    "region_id",
    "home_site_id",
    "employment_type",
    "employment_status",
    "employment_start_date",
    "employment_end_date",
    "created_at",
    "updated_at"
  ],
  "incident_actions": [
    "id",
    "tenant_id",
    "incident_id",
    "description",
    "owner_profile_id",
    "due_date",
    "status",
    "completed_at",
    "verified_by",
    "verified_at",
    "created_at",
    "updated_at"
  ],
  "incident_affected_employees": [
    "id",
    "tenant_id",
    "incident_id",
    "employee_id",
    "involvement",
    "created_at"
  ],
  "incidents": [
    "id",
    "tenant_id",
    "reference_number",
    "site_id",
    "contract_id",
    "category",
    "severity",
    "status",
    "occurred_at",
    "reported_by",
    "description",
    "investigation_notes",
    "corrective_action_summary",
    "closed_by",
    "closed_at",
    "created_at",
    "updated_at"
  ],
  "inventory_items": [
    "id",
    "tenant_id",
    "sku",
    "name",
    "category",
    "unit",
    "reorder_threshold",
    "is_active",
    "created_at",
    "updated_at"
  ],
  "inventory_movements": [
    "id",
    "tenant_id",
    "item_id",
    "site_id",
    "movement_type",
    "quantity",
    "reference",
    "performed_by",
    "created_at"
  ],
  "leave_balance_transactions": [
    "id",
    "tenant_id",
    "employee_id",
    "leave_type_id",
    "period_year",
    "transaction_type",
    "amount",
    "leave_request_id",
    "created_by",
    "created_at"
  ],
  "leave_balances": [
    "id",
    "tenant_id",
    "employee_id",
    "leave_type_id",
    "period_year",
    "opening_balance",
    "accrued",
    "used",
    "pending",
    "adjustment",
    "carried_over",
    "remaining",
    "created_at",
    "updated_at"
  ],
  "leave_policies": [
    "id",
    "tenant_id",
    "leave_type_id",
    "default_annual_days",
    "max_carry_over_days",
    "min_notice_days",
    "requires_documentation",
    "max_consecutive_days",
    "created_at",
    "updated_at"
  ],
  "leave_requests": [
    "id",
    "tenant_id",
    "employee_id",
    "start_date",
    "end_date",
    "reason",
    "status",
    "decided_by",
    "decided_at",
    "created_at",
    "updated_at",
    "leave_type_id",
    "is_half_day",
    "half_day_period",
    "supporting_document_ref",
    "decision_notes",
    "cancelled_at",
    "cancelled_by"
  ],
  "leave_types": [
    "id",
    "tenant_id",
    "name",
    "is_paid",
    "requires_documentation",
    "default_annual_days",
    "status",
    "created_at",
    "updated_at"
  ],
  "notification_deliveries": [
    "id",
    "notification_id",
    "recipient_profile_id",
    "channel",
    "destination",
    "status",
    "attempts",
    "scheduled_for",
    "claimed_at",
    "claim_expires_at",
    "worker_id",
    "sent_at",
    "provider_message_id",
    "error",
    "created_at",
    "updated_at"
  ],
  "notification_preferences": [
    "profile_id",
    "email_enabled",
    "sms_enabled",
    "whatsapp_enabled",
    "quiet_hours_start",
    "quiet_hours_end",
    "updated_at"
  ],
  "notifications": [
    "id",
    "tenant_id",
    "recipient_profile_id",
    "type",
    "title",
    "body",
    "related_entity_table",
    "related_entity_id",
    "link_path",
    "email_status",
    "read_at",
    "created_at"
  ],
  "organizations": [
    "id",
    "name",
    "registration_number",
    "industry",
    "email",
    "phone",
    "website",
    "logo_url",
    "address",
    "timezone",
    "currency",
    "language",
    "status",
    "created_at",
    "updated_at"
  ],
  "performance_reviews": [
    "id",
    "tenant_id",
    "employee_id",
    "reviewer_profile_id",
    "review_period_start",
    "review_period_end",
    "status",
    "overall_rating",
    "manager_comments",
    "employee_comments",
    "finalized_at",
    "created_at",
    "updated_at"
  ],
  "positions": [
    "id",
    "tenant_id",
    "department_id",
    "title",
    "created_at",
    "updated_at",
    "status"
  ],
  "procurement_requests": [
    "id",
    "tenant_id",
    "requested_by",
    "site_id",
    "item_description",
    "quantity",
    "estimated_cost",
    "status",
    "approved_by",
    "approved_at",
    "rejected_reason",
    "created_at",
    "updated_at"
  ],
  "profiles": [
    "id",
    "tenant_id",
    "first_name",
    "last_name",
    "email",
    "phone",
    "avatar_url",
    "status",
    "created_at",
    "updated_at",
    "role"
  ],
  "regions": [
    "id",
    "tenant_id",
    "name",
    "code",
    "created_at",
    "updated_at",
    "status"
  ],
  "shift_definitions": [
    "id",
    "tenant_id",
    "name",
    "start_time",
    "end_time",
    "is_overnight",
    "break_minutes",
    "status",
    "created_at",
    "updated_at"
  ],
  "shift_substitutions": [
    "id",
    "tenant_id",
    "shift_id",
    "original_employee_id",
    "substitute_employee_id",
    "reason",
    "created_at"
  ],
  "shifts": [
    "id",
    "tenant_id",
    "site_id",
    "employee_id",
    "supervisor_id",
    "starts_at",
    "ends_at",
    "status",
    "notes",
    "created_at",
    "updated_at",
    "shift_definition_id"
  ],
  "site_assignments": [
    "id",
    "tenant_id",
    "site_id",
    "employee_id",
    "role_on_site",
    "start_date",
    "end_date",
    "created_at",
    "updated_at"
  ],
  "site_staffing_requirements": [
    "id",
    "tenant_id",
    "site_id",
    "label",
    "required_count",
    "created_at",
    "updated_at"
  ],
  "sites": [
    "id",
    "tenant_id",
    "client_id",
    "region_id",
    "name",
    "address",
    "site_type",
    "status",
    "created_at",
    "updated_at"
  ],
  "skills": [
    "id",
    "tenant_id",
    "name",
    "category",
    "created_at",
    "updated_at"
  ],
  "sla_definitions": [
    "id",
    "tenant_id",
    "contract_id",
    "site_id",
    "name",
    "metric_type",
    "target_value",
    "threshold_operator",
    "measurement_period",
    "is_active",
    "created_at",
    "updated_at"
  ],
  "sla_measurements": [
    "id",
    "tenant_id",
    "sla_definition_id",
    "period_start",
    "period_end",
    "measured_value",
    "target_met",
    "computed_by",
    "computed_at"
  ],
  "sod_rules": [
    "rule_key",
    "description",
    "enforced"
  ],
  "task_checklist_items": [
    "id",
    "tenant_id",
    "task_id",
    "label",
    "sort_order",
    "is_completed",
    "completed_by",
    "completed_at",
    "notes",
    "created_at"
  ],
  "task_comments": [
    "id",
    "tenant_id",
    "task_id",
    "author_id",
    "body",
    "created_at"
  ],
  "task_evidence": [
    "id",
    "tenant_id",
    "task_id",
    "kind",
    "note",
    "submitted_by",
    "created_at"
  ],
  "task_templates": [
    "id",
    "tenant_id",
    "site_id",
    "title",
    "description",
    "instructions",
    "priority",
    "expected_duration_minutes",
    "requires_evidence",
    "default_assignee_id",
    "default_team_id",
    "recurrence_frequency",
    "status",
    "last_generated_on",
    "created_at",
    "updated_at"
  ],
  "tasks": [
    "id",
    "tenant_id",
    "site_id",
    "assignee_id",
    "supervisor_id",
    "title",
    "description",
    "priority",
    "status",
    "due_at",
    "completed_at",
    "created_by",
    "created_at",
    "updated_at",
    "team_id",
    "completed_by",
    "requires_evidence"
  ],
  "team_members": [
    "team_id",
    "employee_id",
    "tenant_id",
    "joined_at"
  ],
  "teams": [
    "id",
    "tenant_id",
    "site_id",
    "name",
    "lead_employee_id",
    "created_at",
    "updated_at",
    "status"
  ],
  "training_enrollments": [
    "id",
    "tenant_id",
    "training_program_id",
    "employee_id",
    "status",
    "enrolled_at",
    "completed_at",
    "result",
    "resulting_qualification_id",
    "created_at",
    "updated_at"
  ],
  "training_programs": [
    "id",
    "tenant_id",
    "name",
    "description",
    "category",
    "is_active",
    "created_at",
    "updated_at"
  ],
  "training_requirements": [
    "id",
    "tenant_id",
    "training_program_id",
    "required_for_role",
    "required_for_site_id",
    "is_active",
    "created_at"
  ],
  "user_scopes": [
    "id",
    "tenant_id",
    "profile_id",
    "scope_type",
    "scope_id",
    "granted_by",
    "created_at"
  ]
};

/** Defaults that depend on "today" (CURRENT_DATE): table -> columns. */
export const CURRENT_DATE_DEFAULTS: Record<string, string[]> = {
  "asset_maintenance_records": [
    "performed_at"
  ],
  "employees": [
    "employment_start_date"
  ],
  "site_assignments": [
    "start_date"
  ]
};

export const COLUMN_DEFAULTS: Record<string, Record<string, unknown>> = {
  "assets": {
    "status": "available"
  },
  "attendance_corrections": {
    "status": "pending"
  },
  "attendance_policies": {
    "early_departure_threshold_minutes": 5,
    "grace_period_minutes": 5,
    "overtime_threshold_minutes": 15
  },
  "attendance_records": {
    "status": "unconfirmed"
  },
  "audit_log": {
    "category": "business",
    "outcome": "success"
  },
  "client_contacts": {
    "is_primary": false
  },
  "clients": {
    "status": "active"
  },
  "compliance_records": {
    "status": "pending"
  },
  "compliance_requirements": {
    "is_active": true
  },
  "contract_documents": {
    "version": 1
  },
  "contracts": {
    "status": "draft"
  },
  "development_actions": {
    "status": "open"
  },
  "employee_documents": {
    "status": "uploaded",
    "version": 1
  },
  "employee_qualifications": {
    "status": "pending_verification"
  },
  "employee_skills": {
    "proficiency_level": "beginner"
  },
  "employees": {
    "employment_status": "active",
    "employment_type": "full_time"
  },
  "incident_actions": {
    "status": "open"
  },
  "incident_affected_employees": {
    "involvement": "involved"
  },
  "incidents": {
    "status": "reported"
  },
  "inventory_items": {
    "is_active": true,
    "unit": "each"
  },
  "leave_balances": {
    "accrued": 0,
    "adjustment": 0,
    "carried_over": 0,
    "opening_balance": 0,
    "pending": 0,
    "used": 0
  },
  "leave_policies": {
    "min_notice_days": 0,
    "requires_documentation": false
  },
  "leave_requests": {
    "is_half_day": false,
    "status": "pending"
  },
  "leave_types": {
    "is_paid": true,
    "requires_documentation": false,
    "status": "active"
  },
  "notification_deliveries": {
    "attempts": 0,
    "status": "pending"
  },
  "notification_preferences": {
    "email_enabled": false,
    "sms_enabled": false,
    "whatsapp_enabled": false
  },
  "notifications": {
    "email_status": "not_sent"
  },
  "organizations": {
    "currency": "ZAR",
    "language": "en",
    "status": "pending",
    "timezone": "Africa/Johannesburg"
  },
  "performance_reviews": {
    "status": "draft"
  },
  "positions": {
    "status": "active"
  },
  "procurement_requests": {
    "status": "requested"
  },
  "profiles": {
    "status": "active"
  },
  "regions": {
    "status": "active"
  },
  "shift_definitions": {
    "break_minutes": 0,
    "is_overnight": false,
    "status": "active"
  },
  "shifts": {
    "status": "scheduled"
  },
  "sites": {
    "status": "onboarding"
  },
  "sla_definitions": {
    "is_active": true,
    "measurement_period": "monthly"
  },
  "sod_rules": {
    "enforced": true
  },
  "task_checklist_items": {
    "is_completed": false,
    "sort_order": 0
  },
  "task_evidence": {
    "kind": "note"
  },
  "task_templates": {
    "priority": "normal",
    "requires_evidence": false,
    "status": "active"
  },
  "tasks": {
    "priority": "normal",
    "requires_evidence": false,
    "status": "open"
  },
  "teams": {
    "status": "active"
  },
  "training_enrollments": {
    "status": "scheduled"
  },
  "training_programs": {
    "is_active": true
  },
  "training_requirements": {
    "is_active": true
  }
};
