/**
 * Framework-level and business-module permission catalogue.
 * Extend this union as each new module lands its own permission set.
 */
export type Permission =
  | 'organization.view'
  | 'organization.manage'
  | 'tenant.switch'
  | 'profile.view_own'
  | 'profile.update_own'
  | 'profile.view_any'
  | 'profile.manage_any'
  | 'org_structure.view'
  | 'org_structure.manage'
  | 'department.view'
  | 'department.manage'
  | 'position.view'
  | 'position.manage'
  | 'employee.view'
  | 'employee.manage'
  | 'team.view'
  | 'team.manage'
  | 'site_assignment.view'
  | 'site_assignment.manage'
  | 'scheduling.view'
  | 'scheduling.manage'
  | 'availability.view'
  | 'availability.manage'
  | 'attendance.view'
  | 'attendance.manage'
  | 'leave.view'
  | 'leave.manage'
  | 'leave.approve'
  | 'task.view'
  | 'task.manage'
  | 'document.view'
  | 'document.manage'
  | 'reports.view'
  | 'reports.export'
  | 'incident.view'
  | 'incident.manage'
  | 'compliance.view'
  | 'compliance.manage';
